In [35]:
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import plotly.graph_objs as go

%matplotlib inline
import pandas as pd
import seaborn as sns
import numpy as np

from geopy.geocoders import Nominatim

In [36]:
lt=pd.read_csv('export.csv', sep=';', 
               error_bad_lines=False,header=None)
lt.head()

b'Skipping line 9843: expected 7 fields, saw 8\n'

,0,1,2,3,4,5,6
0,2018-01-23,De Brug,IJsselstein,groep 6/7,22,Klas naar huis sturen,NaN
1,2018-01-26,Montessori,Hilversum,groep 678,26,Klas verdelen,NaN
2,2018-01-22,De Brug,IJsselstein,groep plusklas,20,Anders of combinatie,NaN
3,2018-01-19,De Brug,IJsselstein,groep 3/4,25,Klas naar huis sturen,NaN
4,2018-01-25,De kleine planeet,deventer,groep 3/4/5,27,Parttimer komt extra dag terug,NaN

In [37]:
# Cleaning

for c in [1,2,3,5]:
    lt[c]=lt[c].str.strip().str.lower()
lt[0]=pd.to_datetime(lt[0])
lt=lt[(lt[0].dt.year==2018)&(lt[0] <pd.Timestamp.today()) ]

In [38]:
lt_ams=lt[lt[2].str.contains('Amsterdam')]
lt_not_ams=lt[~lt[2].str.contains(value)]
ams_vs_rest=pd.DataFrame([lt[5].value_counts()]).T
ams_vs_rest.columns=['Nederland', ]
ams_vs_rest.index.name='Oplossing'
#ams_vs_rest.sort_values(value, ascending=False)
print((ams_vs_rest/ams_vs_rest.sum())["Nederland"][6])
trace1 = go.Bar(
y='Nederland',
x=(ams_vs_rest/ams_vs_rest.sum())["Nederland"][0],
name='Verdeling oplossingen',
orientation = 'h',
marker = dict(
    color = 'rgba(246, 78, 139, 0.6)',
    line = dict(
        color = 'rgba(246, 78, 139, 1.0)',
        width = 3)
)
)

data = [trace1]
layout = go.Layout(
    barmode='stack'
)

NameError: name 'value' is not defined

In [45]:

import datetime
timeFixed = lt[(lt[0]>=datetime.date(2018,1,1)) & (lt[0]<datetime.date(2018,2,1))]

In [46]:
timeFixed

,0,1,2,3,4,5,6
0,2018-01-23,de brug,ijsselstein,groep 6/7,22,klas naar huis sturen,NaN
1,2018-01-26,montessori,hilversum,groep 678,26,klas verdelen,NaN
2,2018-01-22,de brug,ijsselstein,groep plusklas,20,anders of combinatie,NaN
3,2018-01-19,de brug,ijsselstein,groep 3/4,25,klas naar huis sturen,NaN
4,2018-01-25,de kleine planeet,deventer,groep 3/4/5,27,parttimer komt extra dag terug,NaN
5,2018-01-26,kindcentrum devuurvogel,assen,"groep 3,4,5",24,klas verdelen,NaN
6,2018-01-22,de hoeksteen,nieuwlande,groep 5-6,27,parttimer komt extra dag terug,NaN
7,2018-01-23,obs de stegeman,winterswijk,groep 8,26,directie of ib-er etc...,NaN
8,2018-01-25,obs de stegeman,winterswijk,groep 6,27,directie of ib-er etc...,NaN
9,2018-01-26,de kroosduiker,westzaan,groep 4,24,klas naar huis sturen,NaN
10,2018-01-23,de kroosduiker,westzaan,groep 3/4/5,26,klas naar huis sturen,NaN
11,2018-01-17,de wissel,geffen,groep 6,29,parttimer komt extra dag terug,NaN
12,2018-01-19,de wissel,geffen,groep 5,25,klas verdelen,NaN
13,2018-01-25,het palet,heeswijk-dinther,groep 5,24,anders of combinatie,NaN
14,2018-01-25,de albatros,almere,groep 3,24,klas verdelen,NaN
15,2018-01-26,albatros,almere,groep 3,24,klas verdelen,NaN
16,2018-01-26,de weerijs,breda,groep 6,24,klas naar huis sturen,NaN
17,2018-01-26,de bente,emmer compascuum,groep 5/6,25,anders of combinatie,NaN
18,2018-01-26,swbs pork,ter apel,groep 6,29,parttimer komt extra dag terug,NaN
19,2018-01-25,bs de horizon,heerlen,groep 6,30,onbevoegde voor de klas,NaN
20,2018-01-25,bs de horizon,heerlen,groep 4a,25,anders of combinatie,NaN
21,2018-01-24,bs de horizon,heerlen,groep 6a,30,directie of ib-er etc...,NaN
22,2018-01-22,neptunus,amsterdam,groep 1/2,30,onbevoegde voor de klas,NaN
23,2018-01-23,neptunus,amsterdam,groep 1/2,30,onbevoegde voor de klas,NaN
24,2018-01-24,neptunus,amsterdam,groep 1/2,30,onbevoegde voor de klas,NaN
25,2018-01-25,neptunus,amsterdam,groep 1/2,30,onbevoegde voor de klas,NaN
26,2018-01-26,neptunus,amsterdam,groep 1/2,30,onbevoegde voor de klas,NaN
27,2018-01-26,de boemerang,huissen,groep 1-2,26,parttimer komt extra dag terug,NaN
28,2018-01-26,de boemerang,huissen,groep 5-6,28,directie of ib-er etc...,NaN
29,2018-01-25,de boemerang,huissen,groep 1-2,26,directie of ib-er etc...,NaN
...,...,...,...,...,...,...,...
11270,2018-01-19,obs de notenkraker,den haag,groep 7,26,directie of ib-er etc...,NaN
11271,2018-01-22,obs de notenkraker,den haag,groep 7,26,directie of ib-er etc...,NaN
11272,2018-01-23,obs de notenkraker,den haag,groep 7,26,directie of ib-er etc...,NaN
11274,2018-01-24,obs de notenkraker,den haag,groep 7,26,directie of ib-er etc...,NaN
11276,2018-01-25,obs de notenkraker,den haag,groep 7,26,directie of ib-er etc...,NaN
11277,2018-01-26,obs de notenkraker,den haag,groep 7,26,directie of ib-er etc...,NaN
11279,2018-01-29,obs de notenkraker,den haag,groep 7,26,directie of ib-er etc...,NaN
11280,2018-01-30,obs de notenkraker,den haag,groep 7,26,directie of ib-er etc...,NaN
11284,2018-01-31,obs de notenkraker,den haag,groep 7,26,directie of ib-er etc...,NaN
12581,2018-01-19,kindcentrum de regenboog,boekel,groep 8,25,klas verdelen,NaN
12817,2018-01-23,het mozaiek,houten,groep 8,23,klas verdelen,NaN
12920,2018-01-09,smdb de ark,oud-vossemeer,groep 4,10,klas verdelen,NaN
12921,2018-01-10,smdb de ark,oud-vossemeer,groep 3-4-5,30,parttimer komt extra dag terug,NaN
12922,2018-01-11,smdb de ark,oud-vossemeer,groep 5,12,klas verdelen,NaN
13279,2018-01-08,letterland,almere,groep 7/8,23,directie of ib-er etc...,NaN
13281,2018-01-29,letterland,almere,groep 5,24,klas verdelen,NaN
13460,2018-01-25,de wegwijzer,heerlen,groep 7,27,onbevoegde voor de klas,NaN
13461,2018-01-26,de wegwijzer,heerlen,groep 1/2,23,onbevoegde voor de klas,NaN
13520,2018-01-12,pcb de ark,almere,groep 4,26,onbevoegde voor de klas,NaN
13521,2018-01-19,pcb de ark,almere,groep 4,26,onbevoegde voor de klas,NaN
13522,2018-01-26,pcb de ark,almere,groep 4,26,onbevoegde voor de klas,NaN
13534,2018-01-09,pcb de ark,almere,groep 7,18,invaller via detacheringsbureau,NaN
13535,2018-01-16,pcb de ark,almere,groep 7,18,invaller via detacheringsbureau,NaN
13536,2018-01-23,pcb de ark,almere,groep 7,18,invaller via detacheringsbureau,NaN
13537,2018-01-30,pcb de ark,almere,groep 7,18,invaller via detacheringsbureau,NaN
13696,2018-01-10,obssprinkels,meppel,groep 4/5,24,parttimer komt extra dag terug,NaN
13697,2018-01-25,obssprinkels,meppel,groep 1,26,parttimer komt extra dag terug,NaN
13698,2018-01-29,obssprinkels,meppel,groep 1,26,parttimer komt extra dag terug,NaN
13699,2018-01-30,obssprinkels,meppel,groep gym,24,anders of combinatie,NaN
13700,2018-01-30,obssprinkels,meppel,groep 7,25,parttimer komt extra dag terug,NaN

In [54]:
lt=pd.read_csv('export.csv', sep=';', 
               error_bad_lines=False,header=None)

bla=pd.read_csv('cityLatLong.csv', sep='\t', 
               error_bad_lines=False)

b'Skipping line 9843: expected 7 fields, saw 8\n'

In [57]:
lt[2]=lt[2].str.strip().str.lower()

In [62]:
lt.rename(columns={2: 'city'}, inplace=True)
lt.head()

,0,1,city,3,4,5,6
0,2018-01-23,De Brug,ijsselstein,groep 6/7,22,Klas naar huis sturen,NaN
1,2018-01-26,Montessori,hilversum,groep 678,26,Klas verdelen,NaN
2,2018-01-22,De Brug,ijsselstein,groep plusklas,20,Anders of combinatie,NaN
3,2018-01-19,De Brug,ijsselstein,groep 3/4,25,Klas naar huis sturen,NaN
4,2018-01-25,De kleine planeet,deventer,groep 3/4/5,27,Parttimer komt extra dag terug,NaN

In [65]:
lt

,0,1,city,3,4,5,6
0,2018-01-23,De Brug,ijsselstein,groep 6/7,22,Klas naar huis sturen,NaN
1,2018-01-26,Montessori,hilversum,groep 678,26,Klas verdelen,NaN
2,2018-01-22,De Brug,ijsselstein,groep plusklas,20,Anders of combinatie,NaN
3,2018-01-19,De Brug,ijsselstein,groep 3/4,25,Klas naar huis sturen,NaN
4,2018-01-25,De kleine planeet,deventer,groep 3/4/5,27,Parttimer komt extra dag terug,NaN
5,2018-01-26,Kindcentrum DeVuurvogel,assen,"groep 3,4,5",24,Klas verdelen,NaN
6,2018-01-22,De Hoeksteen,nieuwlande,groep 5-6,27,Parttimer komt extra dag terug,NaN
7,2018-01-23,Obs de Stegeman,winterswijk,groep 8,26,Directie of IB-er etc...,NaN
8,2018-01-25,Obs de Stegeman,winterswijk,groep 6,27,Directie of IB-er etc...,NaN
9,2018-01-26,De Kroosduiker,westzaan,groep 4,24,Klas naar huis sturen,NaN
10,2018-01-23,De Kroosduiker,westzaan,groep 3/4/5,26,Klas naar huis sturen,NaN
11,2018-01-17,De Wissel,geffen,groep 6,29,Parttimer komt extra dag terug,NaN
12,2018-01-19,De Wissel,geffen,groep 5,25,Klas verdelen,NaN
13,2018-01-25,Het Palet,heeswijk-dinther,groep 5,24,Anders of combinatie,NaN
14,2018-01-25,De albatros,almere,groep 3,24,Klas verdelen,NaN
15,2018-01-26,Albatros,almere,groep 3,24,Klas verdelen,NaN
16,2018-01-26,De Weerijs,breda,groep 6,24,Klas naar huis sturen,NaN
17,2018-01-26,De Bente,emmer compascuum,groep 5/6,25,Anders of combinatie,NaN
18,2018-01-26,swbs Pork,ter apel,groep 6,29,Parttimer komt extra dag terug,NaN
19,2018-01-25,Bs De Horizon,heerlen,groep 6,30,Onbevoegde voor de klas,NaN
20,2018-01-25,Bs De Horizon,heerlen,groep 4a,25,Anders of combinatie,NaN
21,2018-01-24,Bs De Horizon,heerlen,groep 6a,30,Directie of IB-er etc...,NaN
22,2018-01-22,Neptunus,amsterdam,groep 1/2,30,Onbevoegde voor de klas,NaN
23,2018-01-23,Neptunus,amsterdam,groep 1/2,30,Onbevoegde voor de klas,NaN
24,2018-01-24,Neptunus,amsterdam,groep 1/2,30,Onbevoegde voor de klas,NaN
25,2018-01-25,Neptunus,amsterdam,groep 1/2,30,Onbevoegde voor de klas,NaN
26,2018-01-26,Neptunus,amsterdam,groep 1/2,30,Onbevoegde voor de klas,NaN
27,2018-01-26,De Boemerang,huissen,groep 1-2,26,Parttimer komt extra dag terug,NaN
28,2018-01-26,De Boemerang,huissen,groep 5-6,28,Directie of IB-er etc...,NaN
29,2018-01-25,De boemerang,huissen,groep 1-2,26,Directie of IB-er etc...,NaN
...,...,...,...,...,...,...,...
13740,2018-03-29,OBS Olympus,amsterdam,groep 3,15,Directie of IB-er etc...,NaN
13741,2018-03-29,Obs 't Joppe,nieuw-vennep,groep 6,20,Parttimer komt extra dag terug,NaN
13742,2018-03-29,Obs 't Joppe,nieuw-vennep,groep 5,25,Parttimer komt extra dag terug,NaN
13743,2018-03-29,De Bijenkorf,assendelft,groep 3-4-5,27,Klas verdelen,NaN
13744,2018-03-29,SBO De Tandem,uden,groep 7,-4,Klas naar huis sturen,NaN
13745,2018-03-29,Kameleon,doorn,groep 7,25,Onbevoegde voor de klas,NaN
13746,2018-03-29,Kameleon,doorn,groep 5/6,26,Invaller via detacheringsbureau,NaN
13747,2018-03-29,ASG De Flierefluiter,almere,groep 7-8,27,Onbevoegde voor de klas,NaN
13748,2018-03-29,ASG de Flierefluiter,almere,groep 8,28,Anders of combinatie,NaN
13749,2018-03-29,Toermalijn,uithoorn,groep 5,24,Anders of combinatie,NaN
13750,2018-03-23,De Duinroos Zanderij,katwijk,groep 8,29,Directie of IB-er etc...,NaN
13751,2018-03-28,De Duinroos Zanderij,katwijk,groep 1c,25,Klas naar huis sturen,NaN
13752,2018-03-28,CBS Avonturijn,hilversum,groep 5/6,25,Parttimer komt extra dag terug,NaN
13753,2018-03-29,CBS Avonturijn,hilversum,groep 5/6,26,Anders of combinatie,NaN
13754,2018-03-27,Bloemcampschool,wassenaar,groep 5,28,Klas verdelen,NaN
13755,2018-03-28,De Graankorrel,kudelstaart,groep 5,21,Onbevoegde voor de klas,NaN
13756,2018-03-29,Bs De Bron,neerbeek,groep 4,29,Parttimer komt extra dag terug,NaN
13757,2018-03-28,Bs De Bron,neerbeek,groep 6,26,Onbevoegde voor de klas,NaN
13758,2018-03-27,Bs De Bron,neerbeek,groep 6,26,Parttimer komt extra dag terug,NaN
13759,2018-03-23,Bs De Bron,neerbeek,groep 4,29,Parttimer komt extra dag terug,NaN
13760,2018-03-22,Bs De Bron,neerbeek,groep 4,29,Klas verdelen,NaN
13761,2018-03-22,Bs De Bron,neerbeek,groep 3,21,Directie of IB-er etc...,NaN
13762,2018-03-26,kc Ontdekrijk,capelle aan den ijssel,groep 1/2,27,Invaller via detacheringsbureau,NaN
13763,2018-03-27,kc Ontdekrijk,capelle aan den ijssel,groep 1/2,27,Invaller via detacheringsbureau,NaN
13764,2018-03-23,ASG Zeetuin,almere,groep 8,33,Klas naar huis sturen,NaN
13765,2018-03-21,ASG Zeetuin,almere,groep 8,33,Klas naar huis sturen,NaN
13766,2018-03-22,ASG Zeetuin,almere,groep 7/8,32,Klas naar huis sturen,NaN
13767,2018-03-29,De vuurvogel,tilburg,groep 5-6,25,Klas verdelen,NaN
13768,2018-03-29,De vuurvogel,tilburg,groep 4,27,Invaller via detacheringsbureau,NaN
13769,2018-03-28,De Vuurvogel,tilburg,groep 4,26,Parttimer komt extra dag terug,NaN

In [63]:
joe = pd.merge(lt, bla, on='city', how='inner')

In [66]:
joe.rename(columns={'city': 2, 'lat': 7, 'long': 8}, inplace=True)

In [75]:
cityLatLong = pd.read_csv('cityLatLong.csv', sep='\t')

In [79]:
yo = cityLatLong.loc[cityLatLong['city'].isin(joe[2].unique())]

In [84]:
lt[0]=pd.to_datetime(lt[0])

In [86]:
import datetime
timeFilteredDF = lt[(lt[0]>=datetime.date(2018, 1 ,1)) & (lt[0]<datetime.date(2018 ,2 ,1))]

In [88]:
uniqueTimeFilteredDF = cityLatLong.loc[cityLatLong['city'].isin(timeFilteredDF['city'].unique())]

In [89]:
uniqueTimeFilteredDF

                           city        lat      long
0                   ijsselstein  52.026205  5.028686
1                     hilversum  52.231587  5.173494
2                      deventer  52.249273  6.176131
3                         assen  52.990372  6.553378
4                    nieuwlande  52.691313  6.616811
5                   winterswijk  51.974731  6.722405
6                      westzaan  52.456813  4.773083
7                        geffen  51.742292  5.462088
8              heeswijk-dinther  51.664083  5.466635
9                        almere  52.441759  5.209315
10                        breda  51.564448  4.751230
11             emmer compascuum  52.805873  7.010427
12                     ter apel  52.877717  7.068111
13                      heerlen  50.876277  5.982795
14                    amsterdam  52.374540  4.897976
15                      huissen  51.934410  5.932849
16                    hoogeveen  52.719244  6.465282
17                      zutphen  52.143222  6.204444
18                       leiden  52.151816  4.481109
19                     ugchelen  52.169262  5.900451
20                   oosterhout  51.644472  4.851366
21                    polsbroek  51.987055  4.873784
22                     lelystad  52.536681  5.361072
23                    rotterdam  51.927798  4.488623
24                    hoogezand  53.133009  6.785634
25                   bodegraven  52.092861  4.747455
26                      bantega  52.830288  5.794892
27          berkel en rodenrijs  51.997348  4.470393
28                     aalsmeer  52.265834  4.766170
29                    coevorden  52.652662  6.739324
..                          ...        ...       ...
590                  overijssel  52.425414  6.461061
613                     glimmen  53.138721  6.628281
614                 emmercompas        NaN       NaN
622                   enkhuizen  52.757719  5.320694
623                   sleeuwijk  51.812530  4.940918
625                      helden  51.320791  5.999173
630                      tricht  51.908667  5.261652
631                  beekbergen  52.138933  5.977027
634                      beugen  51.673529  5.937137
635                  oegstgeest  52.183367  4.472129
642                    franeker  53.183828  5.552929
671                 tuitjenhorn  52.739230  4.748727
673                hout-blerick  51.360028  6.126810
674                   naaldwijk  51.992319  4.209760
683                  glanerbrug  52.215550  6.970111
684                   millingen  52.490140  6.263200
689              raamsdonksveer  51.696036  4.875312
698              oud beijerland  51.808122  4.409324
707                     bathmen  52.253309  6.322596
718                     ouddorp  51.801801  3.885134
720                badhoevedorp  52.330044  4.779174
734                  appingedam  53.318725  6.844171
749                 westervoort  51.959756  5.968266
784  nieuwerkerk aan den ijssel  51.966351  4.609027
795               venlo-blerick  51.361744  6.132131
796                   ootmarsum  52.409510  6.902395
832                     wanroij  51.650541  5.817778
835                       laren  52.242531  5.216244
861               oud-vossemeer  51.579497  4.191334
885                      boekel  51.605718  5.674822

[524 rows x 3 columns]

In [90]:
cityLatLong

                       city        lat      long
0               ijsselstein  52.026205  5.028686
1                 hilversum  52.231587  5.173494
2                  deventer  52.249273  6.176131
3                     assen  52.990372  6.553378
4                nieuwlande  52.691313  6.616811
5               winterswijk  51.974731  6.722405
6                  westzaan  52.456813  4.773083
7                    geffen  51.742292  5.462088
8          heeswijk-dinther  51.664083  5.466635
9                    almere  52.441759  5.209315
10                    breda  51.564448  4.751230
11         emmer compascuum  52.805873  7.010427
12                 ter apel  52.877717  7.068111
13                  heerlen  50.876277  5.982795
14                amsterdam  52.374540  4.897976
15                  huissen  51.934410  5.932849
16                hoogeveen  52.719244  6.465282
17                  zutphen  52.143222  6.204444
18                   leiden  52.151816  4.481109
19                 ugchelen  52.169262  5.900451
20               oosterhout  51.644472  4.851366
21                polsbroek  51.987055  4.873784
22                 lelystad  52.536681  5.361072
23                rotterdam  51.927798  4.488623
24                hoogezand  53.133009  6.785634
25               bodegraven  52.092861  4.747455
26                  bantega  52.830288  5.794892
27      berkel en rodenrijs  51.997348  4.470393
28                 aalsmeer  52.265834  4.766170
29                coevorden  52.652662  6.739324
...                     ...        ...       ...
1000             zuidermeer  52.663999  4.975520
1001      oostwold, oldambt  53.215652  7.043184
1002              born (lb)  51.044839  5.837633
1003            roodeschool  53.414617  6.781603
1004            herkenbosch  51.168353  6.102692
1005               avenhorn  52.617738  4.969920
1006                warmond  52.200897  4.525958
1007         surhuisterveen  53.172683  6.154054
1008                de rijp  52.556173  4.842247
1009       sint philipsland  51.633265  4.160483
1010          lichtenvoorde  51.993944  6.565700
1011               macharen  51.802675  5.542677
1012                  megen  51.817166  5.566282
1013    valkenburg a/d geul        NaN       NaN
1014          nieuwe pekela  53.055781  6.960637
1015                  stein  50.973938  5.760869
1016                   lent  51.865864  5.865092
1017           zuid holland  51.996679  4.559740
1018         den hoorn (zh)  52.003360  4.325468
1019  lennisheuvel (boxtel)  51.574320  5.316120
1020               drieborg  53.257924  7.175475
1021                liessel  51.411651  5.830435
1022                   vilt  50.857585  5.809624
1023             nieuwstadt  51.042089  5.861236
1024                   born  51.044839  5.837633
1025            nieuweroord  52.725450  6.564840
1026             noordwolde  52.891558  6.135962
1027             appelascha        NaN       NaN
1028        beneden-leeuwen  51.872420  5.514564
1029               neerbeek  51.256195  5.984346

[1030 rows x 3 columns]

In [83]:
lt[0]

0        2018-01-23
1        2018-01-26
2        2018-01-22
3        2018-01-19
4        2018-01-25
5        2018-01-26
6        2018-01-22
7        2018-01-23
8        2018-01-25
9        2018-01-26
10       2018-01-23
11       2018-01-17
12       2018-01-19
13       2018-01-25
14       2018-01-25
15       2018-01-26
16       2018-01-26
17       2018-01-26
18       2018-01-26
19       2018-01-25
20       2018-01-25
21       2018-01-24
22       2018-01-22
23       2018-01-23
24       2018-01-24
25       2018-01-25
26       2018-01-26
27       2018-01-26
28       2018-01-26
29       2018-01-25
            ...
13740    2018-03-29
13741    2018-03-29
13742    2018-03-29
13743    2018-03-29
13744    2018-03-29
13745    2018-03-29
13746    2018-03-29
13747    2018-03-29
13748    2018-03-29
13749    2018-03-29
13750    2018-03-23
13751    2018-03-28
13752    2018-03-28
13753    2018-03-29
13754    2018-03-27
13755    2018-03-28
13756    2018-03-29
13757    2018-03-28
13758    2018-03-27
13759    2018-03-23
13760    2018-03-22
13761    2018-03-22
13762    2018-03-26
13763    2018-03-27
13764    2018-03-23
13765    2018-03-21
13766    2018-03-22
13767    2018-03-29
13768    2018-03-29
13769    2018-03-28
Name: 0, Length: 13770, dtype: object

In [ ]:
df.isin([1, 3, 12, 'a'])

In [68]:
joe.to_csv("export.csv")

In [39]:
input_value = "amsterdam"



lt_city=lt[lt[2].str.contains(input_value)]
lt_not_city=lt[~lt[2].str.contains(input_value)]
ams_vs_rest=pd.DataFrame([lt_not_city[5].value_counts(),lt_city[5].value_counts()] ).T
ams_vs_rest.columns=['Nederland', input_value]
ams_vs_rest.index.name='Oplossing'

print(ams_vs_rest)

trace1 = go.Bar(
y=['Nederland', input_value],
x=[(ams_vs_rest/ams_vs_rest.sum())["Nederland"][0], (ams_vs_rest/ams_vs_rest.sum())[input_value][0]],
name=ams_vs_rest.index[0],
orientation = 'h',
marker = dict(
    color = 'rgba(127,201,127, 0.6)',
    line = dict(
        color = 'rgba(127,201,127, 1.0)',
        width = 3)
)
)

                                       Nederland  amsterdam
Oplossing
anders of combinatie                        1608        152
directie of ib-er etc...                    1604        194
gepensioneerde voor de klas                  315         48
invaller via detacheringsbureau              569        155
klas naar huis sturen                       2066        177
klas verdelen                               1934        417
onbevoegde voor de klas                     1686        351
ouder met lesbevoegdheid voor de klas         34          4
parttimer komt extra dag terug              2190        128

In [31]:
ams_vs_rest.index

Index(['klas verdelen', 'parttimer komt extra dag terug',
       'klas naar huis sturen', 'onbevoegde voor de klas',
       'directie of ib-er etc...', 'anders of combinatie',
       'invaller via detacheringsbureau', 'gepensioneerde voor de klas',
       'ouder met lesbevoegdheid voor de klas'],
      dtype='object', name='Oplossing')

In [4]:
from IPython import display
import os
def show_app(app, port = 9999, 
             width = 700, 
             height = 350, 
             offline = False,
            in_binder = None):
    in_binder ='JUPYTERHUB_SERVICE_PREFIX' in os.environ if in_binder is None else in_binder
    if in_binder:
        base_prefix = '{}proxy/{}/'.format(os.environ['JUPYTERHUB_SERVICE_PREFIX'], port)
        url = 'https://hub.mybinder.org{}'.format(base_prefix)
        app.config.requests_pathname_prefix = base_prefix
    else:
        url = 'http://localhost:%d' % port
        
    iframe = '<a href="{url}" target="_new">Open in new window</a><hr><iframe src="{url}" width={width} height={height}></iframe>'.format(url = url, 
                                                                                  width = width, 
                                                                                  height = height)
    
    display.display_html(iframe, raw = True)
    if offline:
        app.css.config.serve_locally = True
        app.scripts.config.serve_locally = True
    return app.run_server(debug=False, # needs to be false in Jupyter
                          host = '0.0.0.0',
                          port=port)

In [5]:
import plotly.figure_factory as ff

app = dash.Dash()
app.layout = html.Div([
    dcc.Dropdown(
        id='my-dropdown',
            options=[{'label':name, 'value':name} for name in lt[2].unique()],
        value='amsterdam'
    ),
    dcc.Graph(id='my-table'),
    html.Div(id='my-graph')
])


@app.callback(
    dash.dependencies.Output('my-table', 'figure'),
    [dash.dependencies.Input('my-dropdown', 'value')])
def update_table(value):
    lt_value=lt[lt[2].str.contains(value)]
    lt_not_value=lt[~lt[2].str.contains(value)]
    value_vs_rest=pd.DataFrame([lt_not_value.groupby(5)[4].mean(),lt_value.groupby(5)[4].mean()] ).T
    value_vs_rest.columns=['rest', value]
    value_vs_rest['Oplossing'] = value_vs_rest.index
    #value_vs_rest.index.name='Oplossing'
    value_vs_rest.sort_values(value, ascending=False)
    new_table_figure = ff.create_table(value_vs_rest)
    return new_table_figure

@app.callback(
    dash.dependencies.Output('my-graph', 'children'),
    [dash.dependencies.Input('my-dropdown', 'value')])
def update_graph(value):
    # maak hier de data aan die ik per stad wil doen.
    # return hier de hele graph met die data.
    lt_value=lt[lt[2].str.contains(value)]
    lt_not_value=lt[~lt[2].str.contains(value)]
    value_vs_rest=pd.DataFrame([lt_not_value.groupby(5)[4].sum(),lt_value.groupby(5)[4].sum()] ).T
    value_vs_rest.columns=['rest', value]
    value_vs_rest['Oplossing'] = value_vs_rest.index
    #value_vs_rest.index.name='Oplossing'
    value_vs_rest.sort_values(value, ascending=False)
    print(type(value_vs_rest))
    items = (value_vs_rest/value_vs_rest.sum()).sort_values(value)[value]
    joe = (value_vs_rest/value_vs_rest.sum()).sort_values(value)["rest"]
    return dcc.Graph(
    id='myGraph',
    figure={
        'data':[
            {'y': value_vs_rest['Oplossing'], 'x': items, 'type': 'bar', 'name': value, 'orientation': 'h'},
            {'y': value_vs_rest['Oplossing'], 'x': joe, 'type': 'bar', 'name': "rest", 'orientation': 'h'},
        ],
        'layout': {
            'title': "Percentage oplossingen per kind in een uitgevallen klas in Amsterdam"
        }
    }
    )

In [6]:
import plotly.figure_factory as ff

app = dash.Dash()
app.layout = html.Div([
    dcc.Dropdown(
        id='my-dropdown',
            options=[{'label':name, 'value':name} for name in lt[2].unique()],
        value='amsterdam'
    ),
    html.Div(id='my-graph'),
    html.Div(id='my-graph2'),
    dcc.Graph(id='my-table'),
])


@app.callback(
    dash.dependencies.Output('my-table', 'figure'),
    [dash.dependencies.Input('my-dropdown', 'value')])
def update_table(value):
    lt_value=lt[lt[2].str.contains(value)]
    lt_not_value=lt[~lt[2].str.contains(value)]
    value_vs_rest=pd.DataFrame([lt_not_value.groupby(5)[4].mean(),lt_value.groupby(5)[4].mean()] ).T
    value_vs_rest.columns=['rest', value]
    value_vs_rest['Oplossing'] = value_vs_rest.index
    value_vs_rest.sort_values(value, ascending=False)
    new_table_figure = ff.create_table(value_vs_rest)
    return new_table_figure

@app.callback(
    dash.dependencies.Output('my-graph', 'children'),
    [dash.dependencies.Input('my-dropdown', 'value')])
def update_graph(value):
    lt_value=lt[lt[2].str.contains(value)]
    lt_not_value=lt[~lt[2].str.contains(value)]
    value_vs_rest=pd.DataFrame([lt_not_value.groupby(5)[4].sum(),lt_value.groupby(5)[4].sum()] ).T
    value_vs_rest.columns=['rest', value]
    value_vs_rest.sort_values(value, ascending=False)

    return dcc.Graph(
    id='myGraph',
    figure={
        'data':[
            {'y': value_vs_rest.index, 'x': (value_vs_rest/value_vs_rest.sum()).sort_values(value)[value], 'type': 'bar', 'name': value, 'orientation': 'h'},
            {'y': value_vs_rest.index, 'x': (value_vs_rest/value_vs_rest.sum()).sort_values(value)["rest"], 'type': 'bar', 'name': "rest", 'orientation': 'h'},
        ],
        'layout': { 
            'title': "Percentage oplossingen per kind in een uitgevallen klas in " + value + " en in de rest van Nederland",
            'margin' : {'l': 230, 'b': 40, 't': 50, 'r': 5}
        }
    }
    )

@app.callback(
    dash.dependencies.Output('my-graph2', 'children'),
    [dash.dependencies.Input('my-dropdown', 'value')])
def update_graph(value):
    lt_ams=lt[lt[2].str.contains(value)]
    lt_not_ams=lt[~lt[2].str.contains(value)]
    ams_vs_rest=pd.DataFrame([lt_not_ams[5].value_counts(),lt_ams[5].value_counts()] ).T
    ams_vs_rest.columns=['rest', value]
    ams_vs_rest.index.name='Oplossing'
    ams_vs_rest.sort_values(value, ascending=False)

    return dcc.Graph(
    id='myGraph2',
    figure={
        'data':[
            {'y': ams_vs_rest.index, 'x': (ams_vs_rest/ams_vs_rest.sum()).sort_values(value)[value], 'type': 'bar', 'name': value, 'orientation': 'h'},
            {'y': ams_vs_rest.index, 'x': (ams_vs_rest/ams_vs_rest.sum()).sort_values(value)["rest"], 'type': 'bar', 'name': "rest", 'orientation': 'h'},
        ],
        'layout': {
            'title': "Percentage oplossingen per uitgevallen klas in " + value + " en in de rest van Nederland" ,
            'margin' : {'l': 230, 'b': 40, 't': 50, 'r': 5}
        }
    }
    )

In [7]:
show_app(app)

 * Running on http://0.0.0.0:9999/ (Press CTRL+C to quit)
127.0.0.1 - - [11/Jun/2018 12:50:39] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2018 12:50:39] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2018 12:50:39] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2018 12:50:39] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2018 12:50:39] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2018 12:50:40] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2018 16:47:36] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2018 16:47:36] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2018 16:47:36] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2018 16:47:59] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2018 16:47:59] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2018 16:48:00] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2018 16:48:35] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2018 16:48:35] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2018 16:48:35] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2018 16:48:39] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2018 16:48:39] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2018 16:48:39] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:00:49] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:00:49] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:00:49] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:00:58] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:00:58] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:00:58] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:01:25] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:01:25] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:01:25] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:01:30] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:01:30] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:01:30] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:01:34] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:01:34] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:01:34] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:01:37] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:01:37] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:01:37] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:01:40] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:01:40] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 11:01:40] "POST /_dash-update-component HTTP/1.1" 200 -

In [ ]:
cities = lt[2].unique()
cityLatLong = pd.DataFrame(columns=['lat', 'long'], index=cities)

In [8]:
from geopy.exc import GeocoderTimedOut
geolocator = Nominatim()

def do_geocode(geoString):
    try:
        return geolocator.geocode(geoString)
    except GeocoderTimedOut:
        return do_geocode(geoString)

for city in cities:
    geoString = city + ", Nederland"
    location = do_geocode(geoString)
    if location:
        cityLatLong.loc[city].lat = location.latitude
        cityLatLong.loc[city].long = location.longitude 
    else:
        print(city)

zupthen
rijswijk z-h
kloosterhasr
poorugaal
krinpen aan den ijssel
amsterdam zo

KeyboardInterrupt:

In [ ]:
cityLatLong.to_csv('cityLatLong.csv', sep='\t')

In [ ]:
mapbox_access_token = 'pk.eyJ1IjoicmdpbmduYWdlbCIsImEiOiJjamc1OGN5dDMxNjgzMndwcWJkYzhwMjI4In0.18AdT2y0ZTzoq58R8ws62w'

In [ ]:
import plotly.plotly as py
from plotly.graph_objs import *

data = Data([
    Scattermapbox(
        lat=cityLatLong['lat'],
        lon=cityLatLong['long'],
        mode='markers',
        marker=Marker(
            size=6
        ),
        text=cityLatLong.index,
    )
])
layout = Layout(
    autosize=False,
    hovermode='closest',
    width=1000,
    height=1000,
    mapbox=dict(
        accesstoken=mapbox_access_token,
        bearing=0,
        center=dict(
            lat=52.2,
            lon=5.4
        ),
        pitch=0,
        zoom=6
    ),
)

fig = dict(data=data, layout=layout)

app = dash.Dash()
app.layout = html.Div([
    dcc.Graph(id='my-map',
             figure = fig)
])

In [ ]:
show_app(app)

 * Running on http://0.0.0.0:9999/ (Press CTRL+C to quit)
127.0.0.1 - - [19/Apr/2018 12:00:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2018 12:00:14] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2018 12:00:14] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2018 12:00:19] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2018 12:00:19] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2018 12:00:19] "GET /_dash-dependencies HTTP/1.1" 200 -

In [18]:
cityName = "rotterdam"

lt_value=lt[lt[2].str.contains(cityName)]
value_vs_rest=pd.DataFrame([lt_value.groupby(5)[4].mean()] ).T
print(value_vs_rest)
trace = go.Table(
header=dict(values=['Oplossing', cityName],
            line = dict(color='#7D7F80'),
            fill = dict(color='#a1c3d1'),
            align = ['left'] * 5),
cells=dict(values=[value_vs_rest.index,
                    value_vs_rest[4]],
               line = dict(color='#7D7F80'),
               fill = dict(color='#EDFAFF'),
               align = ['left'] * 5))
layout = dict(width=500, height=300)
data = [trace]
fig = dict(data=data, layout=layout)

                                         4
5
anders of combinatie             19.814815
directie of ib-er etc...         19.263889
gepensioneerde voor de klas      27.000000
invaller via detacheringsbureau  22.187500
klas naar huis sturen            25.647059
klas verdelen                    22.391304
onbevoegde voor de klas          21.488889
parttimer komt extra dag terug   21.000000

In [91]:
joep =pd.read_csv('export.csv', sep=';', 
               error_bad_lines=False,header=None)
joep.head()
joep.fillna(0)

b'Skipping line 9814: expected 7 fields, saw 8\n'

,0,1,2,3,4,5,6
0,2018-01-23,De Brug,IJsselstein,groep 6/7,22,Klas naar huis sturen,0.0
1,2018-01-26,Montessori,Hilversum,groep 678,26,Klas verdelen,0.0
2,2018-01-22,De Brug,IJsselstein,groep plusklas,20,Anders of combinatie,0.0
3,2018-01-19,De Brug,IJsselstein,groep 3/4,25,Klas naar huis sturen,0.0
4,2018-01-25,De kleine planeet,deventer,groep 3/4/5,27,Parttimer komt extra dag terug,0.0
5,2018-01-26,Kindcentrum DeVuurvogel,Assen,"groep 3,4,5",24,Klas verdelen,0.0
6,2018-01-22,De Hoeksteen,Nieuwlande,groep 5-6,27,Parttimer komt extra dag terug,0.0
7,2018-01-23,Obs de Stegeman,Winterswijk,groep 8,26,Directie of IB-er etc...,0.0
8,2018-01-25,Obs de Stegeman,Winterswijk,groep 6,27,Directie of IB-er etc...,0.0
9,2018-01-26,De Kroosduiker,Westzaan,groep 4,24,Klas naar huis sturen,0.0
10,2018-01-23,De Kroosduiker,Westzaan,groep 3/4/5,26,Klas naar huis sturen,0.0
11,2018-01-17,De Wissel,Geffen,groep 6,29,Parttimer komt extra dag terug,0.0
12,2018-01-19,De Wissel,Geffen,groep 5,25,Klas verdelen,0.0
13,2018-01-25,Het Palet,Heeswijk-Dinther,groep 5,24,Anders of combinatie,0.0
14,2018-01-25,De albatros,Almere,groep 3,24,Klas verdelen,0.0
15,2018-01-26,Albatros,Almere,groep 3,24,Klas verdelen,0.0
16,2018-01-26,De Weerijs,Breda,groep 6,24,Klas naar huis sturen,0.0
17,2018-01-26,De Bente,Emmer Compascuum,groep 5/6,25,Anders of combinatie,0.0
18,2018-01-26,swbs Pork,Ter Apel,groep 6,29,Parttimer komt extra dag terug,0.0
19,2018-01-25,Bs De Horizon,Heerlen,groep 6,30,Onbevoegde voor de klas,0.0
20,2018-01-25,Bs De Horizon,Heerlen,groep 4a,25,Anders of combinatie,0.0
21,2018-01-24,Bs De Horizon,Heerlen,groep 6a,30,Directie of IB-er etc...,0.0
22,2018-01-22,Neptunus,Amsterdam,groep 1/2,30,Onbevoegde voor de klas,0.0
23,2018-01-23,Neptunus,Amsterdam,groep 1/2,30,Onbevoegde voor de klas,0.0
24,2018-01-24,Neptunus,Amsterdam,groep 1/2,30,Onbevoegde voor de klas,0.0
25,2018-01-25,Neptunus,Amsterdam,groep 1/2,30,Onbevoegde voor de klas,0.0
26,2018-01-26,Neptunus,Amsterdam,groep 1/2,30,Onbevoegde voor de klas,0.0
27,2018-01-26,De Boemerang,Huissen,groep 1-2,26,Parttimer komt extra dag terug,0.0
28,2018-01-26,De Boemerang,Huissen,groep 5-6,28,Directie of IB-er etc...,0.0
29,2018-01-25,De boemerang,Huissen,groep 1-2,26,Directie of IB-er etc...,0.0
...,...,...,...,...,...,...,...
16182,2018-06-07,ASG obs de archipel,almere,groep 4b,26,Klas verdelen,0.0
16183,2018-06-06,Pieter Jelles Troelstraschool,Amsterdam,"groep montessori gecombineerd 3,4,5",25,Onbevoegde voor de klas,0.0
16184,2018-06-06,Pieter Jelles Troelstraschool,Amsterdam,groep 1/2 a,27,Onbevoegde voor de klas,0.0
16185,2018-05-14,Daltonschool Rijnsweerd,Utrecht,groep 8,29,Parttimer komt extra dag terug,0.0
16186,2018-05-15,Daltonschool Rijnsweerd,Utrecht,groep 8,29,Parttimer komt extra dag terug,0.0
16187,2018-05-17,Daltonschool Rijnsweerd,Utrecht,groep 1/2,24,Klas verdelen,0.0
16188,2018-05-21,Daltonschool Rijnsweerd,Utrecht,groep 8,29,Parttimer komt extra dag terug,0.0
16189,2018-05-22,Daltonschool Rijnsweerd,Utrecht,groep 8,29,Parttimer komt extra dag terug,0.0
16190,2018-05-28,Daltonschool Rijnsweerd,Utrecht,groep 8,29,Parttimer komt extra dag terug,0.0
16191,2018-05-29,Daltonschool Rijnsweerd,Utrecht,groep 8,29,Parttimer komt extra dag terug,0.0
16192,2018-05-28,Daltonschool Rijnsweerd,Utrecht,groep 3,27,Klas verdelen,0.0
16193,2018-06-04,Daltonschool Rijnsweerd,Utrecht,groep 8,29,Parttimer komt extra dag terug,0.0
16194,2018-06-05,Daltonschool Rijnsweerd,Utrecht,groep 8,29,Parttimer komt extra dag terug,0.0
16195,2018-06-08,Obs de Noordkaap,Oostwold,groep 5-6,27,Klas naar huis sturen,0.0
16196,2018-06-06,ASG de Kring,Almere,groep 1/2,29,Klas naar huis sturen,0.0
16197,2018-06-07,ASG de Kring,Almere,groep 1/2,29,Anders of combinatie,0.0
16198,2018-06-04,De klimop,Rotterdam,groep 8,23,Anders of combinatie,0.0
16199,2018-06-05,De klimop,Rotterdam,groep 8,23,Anders of combinatie,0.0
16200,2018-06-06,De klimop,Rotterdam,groep 8,23,Anders of combinatie,0.0
16201,2018-06-07,De klimop,Rotterdam,groep 8,23,Anders of combinatie,0.0
16202,2018-06-08,Eben Haezer,Polsbroek,groep 4,18,Onbevoegde voor de klas,0.0
16203,2018-06-08,Kentalis Signis,Amsterdam,groep 7,12,Parttimer komt extra dag terug,0.0
16204,2018-06-08,SWS De Nijewier,Tjalleberd,groep 5/6,29,Klas naar huis sturen,0.0
16205,2018-06-08,St.-Theresia,Lennisheuvel,groep 7/8,28,Klas naar huis sturen,0.0
16206,2018-06-08,ASG Obs De Ontdekking,Almere,groep 3,29,Anders of combinatie,0.0
16207,2018-06-08,Obs Kortland,Krimpen aan den IJssel,groep 3,23,Anders of combinatie,0.0
16208,2018-06-08,Obs Kortland,Krimpen aan den IJssel,groep 4/5,29,Klas naar huis sturen,0.0
16209,2018-06-08,Obs Kortland,Krimpen aan den IJssel,groep 8,29,Invaller via detacheringsbureau,0.0
16210,2018-06-08,Obs Kortland,Krimpen aan den IJssel,groep nkg,7,Klas verdelen,0.0
16211,2018-06-01,De driemaster,Lelystad,groep 7b,24,Klas verdelen,0.0

In [94]:
joep[5]=joep[5].str.strip()

In [95]:
joep[5].unique()

array(['Klas naar huis sturen', 'Klas verdelen', 'Anders of combinatie',
       'Parttimer komt extra dag terug', 'Directie of IB-er etc...',
       'Onbevoegde voor de klas', 'Invaller via detacheringsbureau',
       'Gepensioneerde voor de klas',
       'Ouder met lesbevoegdheid voor de klas', 'Staking'], dtype=object)

In [116]:
joep[5].replace('', '.', inplace=True)

In [118]:
joep[5].unique()

array(['A.Klas naar huis sturen', 'D.Klas verdelen',
       'J.Anders of combinatie', 'E.Parttimer komt extra dag terug',
       'F.Directie of IB-er etc...', 'C.Onbevoegde voor de klas',
       'I.Invaller via detacheringsbureau',
       'H.Gepensioneerde voor de klas',
       'G.Ouder met lesbevoegdheid voor de klas', 'B.Staking'], dtype=object)

In [121]:
joep[5][0]

str

In [124]:
joep.to_csv('export.csv', sep=';', 
               header=None, index=False)

In [122]:
bla = pd.read_csv('export.csv', sep=';', 
               header=None)

In [123]:
bla

,0,1,2,3,4,5,6,7
0,0,2018-01-23,De Brug,IJsselstein,groep 6/7,22,A.Klas naar huis sturen,NaN
1,1,2018-01-26,Montessori,Hilversum,groep 678,26,D.Klas verdelen,NaN
2,2,2018-01-22,De Brug,IJsselstein,groep plusklas,20,J.Anders of combinatie,NaN
3,3,2018-01-19,De Brug,IJsselstein,groep 3/4,25,A.Klas naar huis sturen,NaN
4,4,2018-01-25,De kleine planeet,deventer,groep 3/4/5,27,E.Parttimer komt extra dag terug,NaN
5,5,2018-01-26,Kindcentrum DeVuurvogel,Assen,"groep 3,4,5",24,D.Klas verdelen,NaN
6,6,2018-01-22,De Hoeksteen,Nieuwlande,groep 5-6,27,E.Parttimer komt extra dag terug,NaN
7,7,2018-01-23,Obs de Stegeman,Winterswijk,groep 8,26,F.Directie of IB-er etc...,NaN
8,8,2018-01-25,Obs de Stegeman,Winterswijk,groep 6,27,F.Directie of IB-er etc...,NaN
9,9,2018-01-26,De Kroosduiker,Westzaan,groep 4,24,A.Klas naar huis sturen,NaN
10,10,2018-01-23,De Kroosduiker,Westzaan,groep 3/4/5,26,A.Klas naar huis sturen,NaN
11,11,2018-01-17,De Wissel,Geffen,groep 6,29,E.Parttimer komt extra dag terug,NaN
12,12,2018-01-19,De Wissel,Geffen,groep 5,25,D.Klas verdelen,NaN
13,13,2018-01-25,Het Palet,Heeswijk-Dinther,groep 5,24,J.Anders of combinatie,NaN
14,14,2018-01-25,De albatros,Almere,groep 3,24,D.Klas verdelen,NaN
15,15,2018-01-26,Albatros,Almere,groep 3,24,D.Klas verdelen,NaN
16,16,2018-01-26,De Weerijs,Breda,groep 6,24,A.Klas naar huis sturen,NaN
17,17,2018-01-26,De Bente,Emmer Compascuum,groep 5/6,25,J.Anders of combinatie,NaN
18,18,2018-01-26,swbs Pork,Ter Apel,groep 6,29,E.Parttimer komt extra dag terug,NaN
19,19,2018-01-25,Bs De Horizon,Heerlen,groep 6,30,C.Onbevoegde voor de klas,NaN
20,20,2018-01-25,Bs De Horizon,Heerlen,groep 4a,25,J.Anders of combinatie,NaN
21,21,2018-01-24,Bs De Horizon,Heerlen,groep 6a,30,F.Directie of IB-er etc...,NaN
22,22,2018-01-22,Neptunus,Amsterdam,groep 1/2,30,C.Onbevoegde voor de klas,NaN
23,23,2018-01-23,Neptunus,Amsterdam,groep 1/2,30,C.Onbevoegde voor de klas,NaN
24,24,2018-01-24,Neptunus,Amsterdam,groep 1/2,30,C.Onbevoegde voor de klas,NaN
25,25,2018-01-25,Neptunus,Amsterdam,groep 1/2,30,C.Onbevoegde voor de klas,NaN
26,26,2018-01-26,Neptunus,Amsterdam,groep 1/2,30,C.Onbevoegde voor de klas,NaN
27,27,2018-01-26,De Boemerang,Huissen,groep 1-2,26,E.Parttimer komt extra dag terug,NaN
28,28,2018-01-26,De Boemerang,Huissen,groep 5-6,28,F.Directie of IB-er etc...,NaN
29,29,2018-01-25,De boemerang,Huissen,groep 1-2,26,F.Directie of IB-er etc...,NaN
...,...,...,...,...,...,...,...,...
16182,16182,2018-06-07,ASG obs de archipel,almere,groep 4b,26,D.Klas verdelen,NaN
16183,16183,2018-06-06,Pieter Jelles Troelstraschool,Amsterdam,"groep montessori gecombineerd 3,4,5",25,C.Onbevoegde voor de klas,NaN
16184,16184,2018-06-06,Pieter Jelles Troelstraschool,Amsterdam,groep 1/2 a,27,C.Onbevoegde voor de klas,NaN
16185,16185,2018-05-14,Daltonschool Rijnsweerd,Utrecht,groep 8,29,E.Parttimer komt extra dag terug,NaN
16186,16186,2018-05-15,Daltonschool Rijnsweerd,Utrecht,groep 8,29,E.Parttimer komt extra dag terug,NaN
16187,16187,2018-05-17,Daltonschool Rijnsweerd,Utrecht,groep 1/2,24,D.Klas verdelen,NaN
16188,16188,2018-05-21,Daltonschool Rijnsweerd,Utrecht,groep 8,29,E.Parttimer komt extra dag terug,NaN
16189,16189,2018-05-22,Daltonschool Rijnsweerd,Utrecht,groep 8,29,E.Parttimer komt extra dag terug,NaN
16190,16190,2018-05-28,Daltonschool Rijnsweerd,Utrecht,groep 8,29,E.Parttimer komt extra dag terug,NaN
16191,16191,2018-05-29,Daltonschool Rijnsweerd,Utrecht,groep 8,29,E.Parttimer komt extra dag terug,NaN
16192,16192,2018-05-28,Daltonschool Rijnsweerd,Utrecht,groep 3,27,D.Klas verdelen,NaN
16193,16193,2018-06-04,Daltonschool Rijnsweerd,Utrecht,groep 8,29,E.Parttimer komt extra dag terug,NaN
16194,16194,2018-06-05,Daltonschool Rijnsweerd,Utrecht,groep 8,29,E.Parttimer komt extra dag terug,NaN
16195,16195,2018-06-08,Obs de Noordkaap,Oostwold,groep 5-6,27,A.Klas naar huis sturen,NaN
16196,16196,2018-06-06,ASG de Kring,Almere,groep 1/2,29,A.Klas naar huis sturen,NaN
16197,16197,2018-06-07,ASG de Kring,Almere,groep 1/2,29,J.Anders of combinatie,NaN
16198,16198,2018-06-04,De klimop,Rotterdam,groep 8,23,J.Anders of combinatie,NaN
16199,16199,2018-06-05,De klimop,Rotterdam,groep 8,23,J.Anders of combinatie,NaN
16200,16200,2018-06-06,De klimop,Rotterdam,groep 8,23,J.Anders of combinatie,NaN
16201,16201,2018-06-07,De klimop,Rotterdam,groep 8,23,J.Anders of combinatie,NaN
16202,16202,2018-06-08,Eben Haezer,Polsbroek,groep 4,18,C.Onbevoegde voor de klas,NaN
16203,16203,2018-06-08,Kentalis Signis,Amsterdam,groep 7,12,E.Parttimer komt extra dag terug,NaN
16204,16204,2018-06-08,SWS De Nijewier,Tjalleberd,groep 5/6,29,A.Klas naar huis sturen,NaN
16205,16205,2018-06-08,St.-Theresia,Lennisheuvel,groep 7/8,28,A.Klas naar huis sturen,NaN
16206,16206,2018-06-08,ASG Obs De Ontdekking,Almere,groep 3,29,J.Anders of combinatie,NaN
16207,16207,2018-06-08,Obs Kortland,Krimpen aan den IJssel,groep 3,23,J.Anders of combinatie,NaN
16208,16208,2018-06-08,Obs Kortland,Krimpen aan den IJssel,groep 4/5,29,A.Klas naar huis sturen,NaN
16209,16209,2018-06-08,Obs Kortland,Krimpen aan den IJssel,groep 8,29,I.Invaller via detacheringsbureau,NaN
16210,16210,2018-06-08,Obs Kortland,Krimpen aan den IJssel,groep nkg,7,D.Klas verdelen,NaN
16211,16211,2018-06-01,De driemaster,Lelystad,groep 7b,24,D.Klas verdelen,NaN

In [151]:
slider = [1,6]
timeFilteredDF = lt[(lt[0]>=datetime.date(2018, slider[0] ,1)) & (lt[0]<datetime.date(2018 ,slider[1]+1 ,1))]
uniqueTimeFilteredDF = cityLatLong.loc[cityLatLong['city'].isin(timeFilteredDF['city'].unique())]

def calculateMarkerColor(timeFixed, cityName):
    colors = {
        'Klas naar huis sturen': 'rgb(215,48,39)',
        'Staking': 'rgb(244,109,67)',
        'Onbevoegde voor de klas': 'rgb(253,174,97)',
        'Klas verdelen':'rgb(254,224,139)',
        'Parttimer komt extra dag terug': 'rgb(217,239,139)',
        'Directie of IB-er etc...':'rgb(166,217,106)',
        'Ouder met lesbevoegdheid voor de klas':'rgb(102,189,99)',
        'Gepensioneerde voor de klas':'rgb(26,152,80)',
        'Invaller via detacheringsbureau':'rgb(18,106,56)',
        'Anders of combinatie':'rgb(220,220,220)' }

    lt_value=timeFixed[timeFixed['city'].str.contains(cityName)]

    value_vs_rest=pd.DataFrame([lt_value.groupby(5)[4].sum()] ).T
    return colors[value_vs_rest.idxmax()[4]]

print([calculateMarkerColor(timeFilteredDF, x) for x in list(uniqueTimeFilteredDF['city'])])

lt_value=timeFixed[timeFixed['city'].str.contains(cityName)]

value_vs_rest=pd.DataFrame([lt_value.groupby(5)[4].sum()] ).T
valueWithLeerlingen = value_vs_rest[4]
value_vs_rest.idxmax()[4]

KeyError: 'Klas naar huis sturen '

In [164]:
cityName = 'amsterdam'

lt_value=timeFixed[timeFixed['city'].str.contains(cityName)]

value_vs_rest=pd.DataFrame([lt_value.groupby(5)[4].sum()] ).T
valueWithLeerlingen = value_vs_rest[4]
value_vs_rest.idxmax()[4]

'Klas naar huis sturen'

In [160]:
print(timeFilteredDF)

               0                        1                    city  \
0     2018-01-23                  De Brug             ijsselstein
1     2018-01-26               Montessori               hilversum
2     2018-01-22                  De Brug             ijsselstein
3     2018-01-19                  De Brug             ijsselstein
4     2018-01-25        De kleine planeet                deventer
5     2018-01-26  Kindcentrum DeVuurvogel                   assen
6     2018-01-22             De Hoeksteen              nieuwlande
7     2018-01-23          Obs de Stegeman             winterswijk
8     2018-01-25          Obs de Stegeman             winterswijk
9     2018-01-26           De Kroosduiker                westzaan
10    2018-01-23           De Kroosduiker                westzaan
11    2018-01-17                De Wissel                  geffen
12    2018-01-19                De Wissel                  geffen
13    2018-01-25                Het Palet        heeswijk-dinther
14    2018-01-25             De albatros                   almere
15    2018-01-26                Albatros                   almere
16    2018-01-26               De Weerijs                   breda
17    2018-01-26                 De Bente        emmer compascuum
18    2018-01-26                swbs Pork                ter apel
19    2018-01-25            Bs De Horizon                 heerlen
20    2018-01-25            Bs De Horizon                 heerlen
21    2018-01-24            Bs De Horizon                 heerlen
22    2018-01-22                 Neptunus               amsterdam
23    2018-01-23                 Neptunus               amsterdam
24    2018-01-24                 Neptunus               amsterdam
25    2018-01-25                 Neptunus               amsterdam
26    2018-01-26                 Neptunus               amsterdam
27    2018-01-26             De Boemerang                 huissen
28    2018-01-26             De Boemerang                 huissen
29    2018-01-25             De boemerang                 huissen
...          ...                      ...                     ...
13740 2018-03-29              OBS Olympus               amsterdam
13741 2018-03-29             Obs 't Joppe            nieuw-vennep
13742 2018-03-29             Obs 't Joppe            nieuw-vennep
13743 2018-03-29             De Bijenkorf              assendelft
13744 2018-03-29            SBO De Tandem                    uden
13745 2018-03-29                 Kameleon                   doorn
13746 2018-03-29                 Kameleon                   doorn
13747 2018-03-29     ASG De Flierefluiter                  almere
13748 2018-03-29     ASG de Flierefluiter                  almere
13749 2018-03-29               Toermalijn                uithoorn
13750 2018-03-23     De Duinroos Zanderij                 katwijk
13751 2018-03-28     De Duinroos Zanderij                 katwijk
13752 2018-03-28           CBS Avonturijn               hilversum
13753 2018-03-29           CBS Avonturijn               hilversum
13754 2018-03-27          Bloemcampschool               wassenaar
13755 2018-03-28           De Graankorrel             kudelstaart
13756 2018-03-29               Bs De Bron                neerbeek
13757 2018-03-28               Bs De Bron                neerbeek
13758 2018-03-27               Bs De Bron                neerbeek
13759 2018-03-23               Bs De Bron                neerbeek
13760 2018-03-22               Bs De Bron                neerbeek
13761 2018-03-22               Bs De Bron                neerbeek
13762 2018-03-26            kc Ontdekrijk  capelle aan den ijssel
13763 2018-03-27            kc Ontdekrijk  capelle aan den ijssel
13764 2018-03-23              ASG Zeetuin                  almere
13765 2018-03-21              ASG Zeetuin                  almere
13766 2018-03-22              ASG Zeetuin                  almere
13767 2018-03-29             De vuurvogel                 tilburg
13768 2018-03-29             De vuurvogel                 tilburg
13769 2018-03-28             De Vuurvogel                 tilburg

                    3   4                                5   6
0           groep 6/7  22            Klas naar huis sturen NaN
1           groep 678  26                    Klas verdelen NaN
2      groep plusklas  20             Anders of combinatie NaN
3           groep 3/4  25            Klas naar huis sturen NaN
4         groep 3/4/5  27   Parttimer komt extra dag terug NaN
5         groep 3,4,5  24                    Klas verdelen NaN
6           groep 5-6  27   Parttimer komt extra dag terug NaN
7             groep 8  26         Directie of IB-er etc... NaN
8             groep 6  27         Directie of IB-er etc... NaN
9             groep 4  24            Klas naar huis sturen NaN
10        groep 3/4/5  26            Klas naar huis sturen NaN
11            groep 6  29   Parttimer komt extra dag terug NaN
12            groep 5  25                    Klas verdelen NaN
13            groep 5  24             Anders of combinatie NaN
14            groep 3  24                    Klas verdelen NaN
15            groep 3  24                    Klas verdelen NaN
16            groep 6  24            Klas naar huis sturen NaN
17          groep 5/6  25             Anders of combinatie NaN
18            groep 6  29   Parttimer komt extra dag terug NaN
19            groep 6  30          Onbevoegde voor de klas NaN
20           groep 4a  25             Anders of combinatie NaN
21           groep 6a  30         Directie of IB-er etc... NaN
22          groep 1/2  30          Onbevoegde voor de klas NaN
23          groep 1/2  30          Onbevoegde voor de klas NaN
24          groep 1/2  30          Onbevoegde voor de klas NaN
25          groep 1/2  30          Onbevoegde voor de klas NaN
26          groep 1/2  30          Onbevoegde voor de klas NaN
27          groep 1-2  26   Parttimer komt extra dag terug NaN
28          groep 5-6  28         Directie of IB-er etc... NaN
29          groep 1-2  26         Directie of IB-er etc... NaN
...               ...  ..                              ...  ..
13740         groep 3  15         Directie of IB-er etc... NaN
13741         groep 6  20   Parttimer komt extra dag terug NaN
13742         groep 5  25   Parttimer komt extra dag terug NaN
13743     groep 3-4-5  27                    Klas verdelen NaN
13744         groep 7  -4            Klas naar huis sturen NaN
13745         groep 7  25          Onbevoegde voor de klas NaN
13746       groep 5/6  26  Invaller via detacheringsbureau NaN
13747       groep 7-8  27          Onbevoegde voor de klas NaN
13748         groep 8  28             Anders of combinatie NaN
13749         groep 5  24             Anders of combinatie NaN
13750         groep 8  29         Directie of IB-er etc... NaN
13751        groep 1c  25            Klas naar huis sturen NaN
13752       groep 5/6  25   Parttimer komt extra dag terug NaN
13753       groep 5/6  26             Anders of combinatie NaN
13754         groep 5  28                    Klas verdelen NaN
13755         groep 5  21          Onbevoegde voor de klas NaN
13756         groep 4  29   Parttimer komt extra dag terug NaN
13757         groep 6  26          Onbevoegde voor de klas NaN
13758         groep 6  26   Parttimer komt extra dag terug NaN
13759         groep 4  29   Parttimer komt extra dag terug NaN
13760         groep 4  29                    Klas verdelen NaN
13761         groep 3  21         Directie of IB-er etc... NaN
13762       groep 1/2  27  Invaller via detacheringsbureau NaN
13763       groep 1/2  27  Invaller via detacheringsbureau NaN
13764         groep 8  33            Klas naar huis sturen NaN
13765         groep 8  33            Klas naar huis sturen NaN
13766       groep 7/8  32            Klas naar huis sturen NaN
13767       groep 5-6  25                    Klas verdelen NaN
13768         groep 4  27  Invaller via detacheringsbureau NaN
13769         groep 4  26   Parttimer komt extra dag terug NaN

[13650 rows x 7 columns]

In [158]:
list(uniqueTimeFilteredDF['city'])

['ijsselstein',
 'hilversum',
 'deventer',
 'assen',
 'nieuwlande',
 'winterswijk',
 'westzaan',
 'geffen',
 'heeswijk-dinther',
 'almere',
 'breda',
 'emmer compascuum',
 'ter apel',
 'heerlen',
 'amsterdam',
 'huissen',
 'hoogeveen',
 'zutphen',
 'leiden',
 'ugchelen',
 'oosterhout',
 'polsbroek',
 'lelystad',
 'rotterdam',
 'hoogezand',
 'bodegraven',
 'bantega',
 'berkel en rodenrijs',
 'aalsmeer',
 'coevorden',
 'utrecht',
 'zaandam',
 'veenendaal',
 'maasbree',
 'schoorl',
 'leidschendam',
 'nijmegen',
 'boxmeer',
 'wijchen',
 'vijfhuizen',
 'barneveld',
 'amersfoort',
 'middelharnis',
 'veendam',
 'zoetermeer',
 'diemen',
 'didam',
 'rijen',
 'arnhem',
 'tilburg',
 'zuidwolde gr',
 'zeist',
 'haarlem',
 'elst gld',
 'eext',
 'zwolle',
 'castricum',
 'baarn',
 'dokkum',
 'eck en wiel',
 'metslawier',
 'den haag',
 'zupthen',
 'drachten',
 'siddeburen',
 'venlo',
 'varik',
 'nootdorp',
 'bussum',
 'nieuw vennep',
 'stuifzand',
 'hoogland',
 'doorn',
 'apeldoorn',
 'obdam',
 'harderwijk',
 'oudenhoorn',
 'twello',
 'den bosch',
 'muntendam',
 'koedijk',
 'rijswijk z-h',
 'beuningen',
 'zevenaar',
 'eindhoven',
 'renkum',
 'assendelft',
 'scharendijke',
 'emmen',
 'almelo',
 'de wilp',
 'de goorn',
 'loosdrecht',
 'tilligte',
 'papendrecht',
 'houten',
 'kootstertille',
 'gouda',
 'de weere',
 'sneek',
 'hellevoetsluis',
 'ijmuiden',
 'kloosterhasr',
 'best',
 'zuidwolde',
 'giessenburg',
 'schelluinen',
 'krimpen aan den ijssel',
 'zwaag',
 'schiedam',
 'delft',
 'den helder',
 'oudeschoot',
 'bovenkarspel',
 'hoofddorp',
 'duiven',
 'schoonhoven',
 'groningen',
 'oldeberkoop',
 'heerenveen',
 'hooglanderveen',
 'rheden',
 'musselkanaal',
 'heemskerk',
 'middelburg',
 'voorburg',
 'noord-holland',
 'doetinchem',
 'vianen',
 'spijkenisse',
 'oostrum',
 'maarssen',
 'grave',
 'lisserbroek',
 'vierpolders',
 'dieren',
 'panningen',
 'nieuwegein',
 'amstelveen',
 'hendrik-ido-ambacht',
 'katwijk',
 'pijnacker',
 'peize',
 'nieuw-vennep',
 'overveen',
 'bleiswijk',
 'poorugaal',
 'reigerlaan',
 'itens',
 'made',
 'de meern',
 'moordrecht',
 'tijnje',
 'velp',
 'epe',
 'berkel-enschot',
 'gilze',
 'willemsoord',
 'amsterdan',
 'capelle aan den ijssel',
 'wouw',
 'culemborg',
 'helvoirt',
 'waalre',
 'erm',
 'hauwert',
 'anna paulowna',
 'sint maartensbrug',
 'jubbega',
 'bennekom',
 'ten boer',
 'krinpen aan den ijssel',
 'amsterdam zo',
 'uithuizen',
 'steenwijk',
 'ternaard',
 'aerdenhout',
 'klazienaveen',
 'velserbroek',
 'arcen',
 'luijksgestel',
 'andijk',
 'hulsel',
 'abcoude',
 'hantumhuizen',
 'paesens',
 'driemond',
 'swifterbant',
 'holwerd',
 'slootdorp',
 'leiderdorp',
 'wassenaar',
 'well',
 'kudelstaart',
 'winschoten',
 'stiens',
 'hoorn nh',
 'enschede',
 'woudenberg',
 'uden',
 'ede',
 'dalfsen',
 'den burg (texel)',
 'simpelveld',
 'buurse',
 'alkmaar',
 'burum',
 'broek op langedijk',
 'deurne',
 'harkstede',
 'rozendaal',
 'den burg',
 'beilen',
 'etten-leur',
 'rhoon',
 'poortugaal',
 'alphen aan den rijn',
 'wolvega',
 'huizen',
 'blaricum',
 'hulst',
 'est',
 'krommenie',
 'klarenbeek',
 'keijenborg',
 'haaften',
 'weert',
 'velp (gld)',
 'uithoorn',
 'uithuizermeeden',
 'haren - nb',
 'bedum',
 'zeddam',
 'zwijndrecht',
 'arkel',
 'wichmond',
 'heino',
 'wormer',
 'nieuw bergen',
 'leusden',
 'terneuzen',
 'lutjebroek',
 'kampen',
 'roosendaal',
 'rijswijk gld',
 'gennep',
 'genmep',
 'hollandsche radjng',
 'hollandsche rading',
 'landgraaf',
 'hengelo',
 'moerkapelle',
 'vlaardingen',
 'voorthuizen',
 'sappemeer',
 'schalkwijk',
 'schalwijk',
 'spijk',
 'rijswijk',
 'hoogkarspel',
 'varsseveld',
 'hardenberg',
 'heelweg',
 'westergeest',
 'purmerend',
 'boxtel',
 'dordrecht',
 'holten',
 'woerden',
 'groesbeek',
 'delfzijl',
 'zuidlaren',
 'oud-beijerland',
 'hoorn',
 'cuijk',
 'adorp',
 'raalte',
 'doetinchm',
 'hendrik ido ambacht',
 'al ere',
 'schoonoord',
 'meppel',
 'roden',
 'norg',
 'nieuwkuijk',
 'groningeb',
 'gramsbergen',
 'een',
 'roermond',
 'noordhorn',
 'leek',
 'zuidhorn',
 'molenschot',
 'molenschot.nl',
 'mill',
 'yerseke',
 'geleen',
 'vinkeveen',
 'edd',
 'oud verlaat',
 'oostwold',
 'maarn',
 'gemert',
 'barendrecht',
 'luxwoude',
 'eelde',
 'denhaag',
 'heerhugowaard',
 'pernis',
 'bladel',
 'tiel',
 'oosterhou',
 'stellendam',
 'koog aan de zaan',
 'goes',
 'houte',
 'rosmalen',
 'breukelen',
 'prinsenbeek',
 'heemstede',
 'luttenberg',
 'kloosterhaar',
 'mariënheem',
 'kapelle',
 'wierden',
 'leeuwarden',
 'brummen',
 'heerjansdam',
 'ruinerwold',
 "'s-hertogenbosch",
 'oudewater',
 'lopik',
 'lichtenvoord',
 'teteringen',
 'loo',
 'mook',
 'baarlo',
 'warmenhuizen',
 'bergschenhoek',
 'losser',
 'rolde',
 'beverwijk',
 'hasselt (ov)',
 'bunnik',
 'noordwijk',
 'denekamp',
 'soest',
 'valkenswaard',
 'asterdam',
 'haulerwijk',
 'heiloo',
 'yerske',
 'hulsberg',
 'mijdrecht',
 'horssen',
 'beuningen gld',
 'annen',
 'grootebroek',
 'joure',
 'mierlo',
 'boazum',
 'deinum',
 'tull en ‘t waal',
 'maastricht',
 'ven-zelderheide',
 'daarlerveen',
 'ermelo',
 'beek en donk',
 "'s gravenzande",
 'zoetermeee',
 'nieuw dordrecht',
 'bemmel',
 'sprang-capelle',
 'noordscheschut',
 'ulft',
 'veldhoven',
 'winsum',
 'terwispel',
 'nuis',
 'oppenhuizen',
 'zevenhuizen gr',
 'elim',
 'lennisheuvel',
 'nunspeet',
 'lemmer',
 'den hoorn zh',
 'bovensmilde',
 'doesburg',
 'ijlst',
 'balk',
 'ridderkerk',
 'amterdam',
 'oss',
 'leerdam',
 'meteren',
 'krimpen ad ijssel',
 'bilthoven',
 'zaandijk',
 'oenkerk',
 'rijsenhout',
 'badhoevedotp',
 'voorschoten',
 'gasselternijveen',
 'slagharen',
 'lattrop',
 'maartensdijk',
 'west-graftdijk',
 'hoogersmilde',
 'hasselt',
 'beets',
 'opmeer',
 'vught',
 'biddinghuizen',
 'groet',
 'elst',
 'steenwijkerwold',
 'tuk',
 "'t loo",
 'nui',
 'groningwn',
 'ysselsteyn',
 'nijkerk',
 'silvolde',
 'warns',
 'zeeland',
 'bunschoten',
 'eelde-paterswolde',
 'dodewaard',
 'beltrum',
 'holwierde',
 'elst (utr)',
 'loon op zand',
 'hippolytushoef',
 'steenbergen',
 'gerkesklooster',
 'surhuizum',
 'etten leur',
 'werkendam',
 'dedemsvaart',
 'exloo',
 'buitenpost',
 'spakenburg',
 'kaatsheuvel',
 'burgum',
 'geldermalsen',
 'drogeham',
 'helmond',
 'sondel',
 'nieuw- vennep',
 'nijemirdum',
 'domburg',
 'gorinchem',
 'stadskanaal',
 'dorst',
 'jorwert',
 'rumpt',
 'limmen',
 'breugel',
 'ophemert',
 'sittard',
 'maassluis',
 'rijnsburg',
 'ooltgensplaat',
 'schoondijke',
 'lonneker',
 'de kwakel',
 'opheusden',
 'ijzendoorn',
 'kesteren',
 'kortenhoef',
 'berkel',
 'rilland',
 'riel',
 'nieuw-dordrecht',
 'oldekerk',
 'reek',
 'deil',
 'emmeloord',
 'vaassen',
 'bunschoten spakenburg',
 'hengelo gld',
 'rijssen',
 'bocholtz',
 "'s heerenbroek",
 'tjalleberd',
 'nijmegn',
 'westerhaar-vriezenveensewijk',
 'boornbergum',
 'brunssum',
 'schaijk',
 'zelhem',
 'heeze',
 'harskamo',
 'harskamp',
 'gorredijk',
 'den haaag',
 'egmond aan den hoef',
 'bavel',
 'vreeland',
 'oldeholtpade',
 'son en breugel',
 'udenhout',
 'harkema',
 'bolsward',
 'eenrum',
 'sint annaparochie',
 'slochteren',
 'ureterp',
 'sint jacobiparochie',
 'mûnein',
 'oosterwolde',
 'hengelo (gld)',
 'wanneperveen',
 'winsum gn',
 'westerhaar - vroezenveensewijk',
 'westerhaar- vroezenveensewijk',
 'wijk bij duurstede',
 'hazerswoude dorp',
 'rhenoy',
 'venhorst',
 'oisterwijk',
 'vleuten',
 'heesch',
 'wildervank',
 'oranjewoud',
 'hertme',
 'lieshout',
 'oldenzaal',
 'veeningen',
 'oudenbosch',
 'goutum',
 'waddinxveen',
 'sevenum',
 'ens',
 'nieuwolda',
 'son',
 'heeg',
 'deest',
 'berkel en rodernijs',
 'foxhol',
 'dronten',
 'olst',
 'den boscb',
 'driebergen',
 'wageningen',
 'muiden',
 'amsterdam zuidoost',
 'weesp',
 'assendeflt',
 'rotterdamse',
 'schagen',
 'noordwijkerhout',
 'zevenhuizen (gr)',
 'linschoten',
 'vinkel',
 'waalwijk',
 'tiel passewaaij',
 'aalten',
 'verndam',
 'medemblkk',
 'harmelen',
 'elburg',
 'naarden',
 'schipluiden',
 'tegelen',
 'hollandscheveld',
 'roderwolde',
 'someren - eind',
 'posterholt',
 'horn',
 'hoogvliet',
 'geldrop',
 'dalfsen/hoonhorst',
 'waardenburg',
 'ryptsjerk',
 'zaaandam',
 'riethoven',
 'damwald',
 'den burg (texel_',
 'boven pekela',
 'ammerstol',
 'urk',
 'heiligerlee',
 'wapse',
 'wapserveen',
 'ansterdam',
 'oude-tonge',
 'genemuiden',
 'swolgen',
 'emmer-compascuum',
 'overijssel',
 'haren gn',
 'hoedekenskerke',
 'krabbendijke',
 'bakhuizen',
 'diever',
 'nietap',
 'hoofdorp',
 'smilde',
 'witmarsum',
 'noord-scharwoude',
 'kamerik',
 '‘s-hertogenbosch',
 'ijhorst',
 'zwanenburg',
 'eerbeek',
 'marknesse',
 'harlingen',
 'blokker',
 'boskoop',
 'haren',
 'sint pancras',
 'vessem',
 'glimmen',
 'emmercompas',
 'goor',
 'drachtstercompagnie',
 'baexem',
 'maasdijk',
 'wezep',
 'de rips',
 'medemblik',
 'enkhuizen',
 'sleeuwijk',
 'hank',
 'helden',
 'koudekerk aan den rijn',
 'barchem',
 'wirdum',
 'bitgummole',
 'tricht',
 'beekbergen',
 'ommeren',
 'ittervoort',
 'beugen',
 'oegstgeest',
 'enter',
 'thesinge',
 'zwartemeer',
 'neede',
 'akkrum',
 'hoek van holland',
 'franeker',
 'bergen op zoom',
 'zierikzee',
 'beetsterzwaag',
 'nijeholtpade',
 'babberich',
 'vogelwaarde',
 'diepenveen',
 'bruinisse',
 'busssum',
 'wedde',
 'zaltbommel',
 'duivendrecht',
 'hilegom',
 'hillegom',
 "'t veld",
 'nijbroek',
 'nuenen',
 'bleskensgraaf',
 'grou',
 'julianadorp',
 'appelscha',
 'zandvoort',
 'tholen',
 'pieterburen',
 'waspik',
 'lienden',
 'oosterbeek',
 'koekange',
 'tuitjenhorn',
 'almen',
 'hout-blerick',
 'naaldwijk',
 'nieuw amsterdam',
 'soesterberg',
 'ederveen',
 'reuver',
 'kollumerpomp',
 'mantgum',
 'elst (ut.)',
 'wijthmen',
 'glanerbrug',
 'millingen',
 'zetten',
 'het dorp ee',
 'axel',
 'wilhelminaoord',
 'raamsdonksveer',
 'oostwold oldambt',
 'oostzaan',
 'beek-ubbergen',
 'loenen aan de vecht',
 'reeuwijk',
 'ijsselmuiden',
 'wilp',
 'kootwijkerbroek',
 'oud beijerland',
 'de bilt',
 'oudwoude',
 'in papendrecht',
 'haaksbergen',
 'donkerbroek',
 'utrechty',
 'westerbork',
 'waskemeer',
 'bathmen',
 'wiuwert',
 'vries',
 'oostburg',
 'haar',
 'nieuwleusen',
 'almere p',
 'nijkerkerveen',
 'laag zuthem',
 'gelderland',
 'zuidbroek',
 'ouddorp',
 'veghel',
 'badhoevedorp',
 'ten post',
 'eesveen',
 'utrecht.',
 'tzummarum',
 'lemelerveld',
 'terheijden',
 'grijpskerk',
 'niekekr(gn)',
 'westerhaar- vriezenveensewijk',
 'westerhaar vriezenveensewijk',
 'akersloot',
 'eemnes',
 'nieuw-weerdinge',
 'appingedam',
 'bakkeveen',
 'halsteren',
 'oude pekela',
 'hoornaar',
 'damwoude',
 'damwâld',
 'vaals',
 'spaarndam',
 'vorden',
 'hansweert',
 'heenvliet',
 'hommerts',
 'asten',
 'nieuwkoop',
 'westervoort',
 'lobith',
 'diepenheim',
 'monnickendam',
 'oudehaske',
 'rottum',
 'mussel',
 'ingen',
 'wilnis',
 'oldemarkt',
 'amsterda',
 'wemeldinge',
 'haarzuilens',
 'burdaard',
 'westwoud',
 'hoevelaken',
 'spijk gn',
 'feanwâlden',
 'wehe den hoorn',
 'wehe-den hoorn',
 'volendam',
 'oudehorne',
 'barger compascuum',
 'elsloo',
 'de knipe',
 'makkum',
 'sassenheim',
 'ommen',
 'herveld',
 'kwadijk',
 'warder',
 'wagenborgen',
 'langezwaag',
 'blijham',
 'gouderak',
 'nieuwerkerk aan den ijssel',
 'earnew6ald',
 'laren gld',
 'vlaardimgen',
 'capelle aan de ijssel',
 'limmem',
 'breezand',
 'weiteveen',
 'rhenen',
 'krimpen a d ijssel',
 'voorhout',
 'venlo-blerick',
 'ootmarsum',
 'deurningen',
 'eibergen',
 'alphen ad rijn',
 'vlissingen',
 'saasveld',
 'oldehove',
 'overdinkel',
 'nijverdal',
 'uffelte',
 'almel',
 'benschop',
 'grolloo',
 '‘s gravenzande',
 'zwartsluis',
 'wolphaartsdijk',
 "'t harde",
 'eelderwolde',
 'tynaarlo',
 'rotterdam zuid',
 '2e exloermond',
 'staphorst',
 'noord scharwoude',
 'alphen a/d rijn',
 'borne',
 'krimpen a/d ijssel',
 'creil',
 'oosthuizen',
 'wommels',
 'vriescheloo',
 'uitgeest',
 'marum',
 'zeerijp',
 'boerakker',
 'eastermar',
 'kuinre',
 'wanroij',
 'vollenhove',
 'zuidalaren',
 'laren',
 'westeremden',
 'bloemendaal',
 'de lutte',
 'bunschoten-spakenburg',
 'beuningen, gelderland',
 'emmeloorc',
 'krimpen aan drn ijssel',
 'tolbert',
 'opende',
 's-gravenzande',
 'katwijk zh',
 '‘s hertogenbosch',
 'rasquert',
 'wervershoof',
 'makkinga',
 'wijster',
 'willemstad',
 'hardinxveld-giessendam',
 'ottersum',
 'sint anthonis',
 "'s-hertogenboshc",
 'dwingeloo',
 'fijnaart',
 'zundert',
 'wesepe',
 'oud-vossemeer',
 'dongen',
 'grotenhof',
 "'s hertogenbosch",
 'hindeloopen',
 'workum',
 'goirle',
 'dinteloord',
 'lepelstraat',
 'st. willebrord',
 'oostrum lb',
 'rothem',
 'frieschepalen',
 'heusden',
 'brakel',
 'middelrode',
 'arnhen',
 'sas van gent',
 'zevenhuizen',
 'giesbeek',
 'parrega',
 'austerlitz',
 'bergentheim',
 'spankeren',
 'boekel',
 'lage mierde',
 'angerlo',
 'noordeinde',
 'hengstdijk',
 'huis ter heide',
 'hoogerheide',
 'woensdrecht',
 'aardenburg',
 'ravenstein',
 'koningsbosch',
 'bingelrade',
 'jabeek',
 'gulpen',
 'venray',
 'nieuwdorp',
 'tst',
 'wanroj',
 'heythuysen',
 'langenboom',
 'buchten',
 'druten',
 'hummelo',
 'ulestraten',
 'handel',
 'roggel',
 'blerick',
 'afferden',
 'wessem',
 'niftrik',
 'heteren',
 'nistelrode',
 'hoonhorst',
 'angeren',
 'mesch',
 'kerkrade',
 'biezenmortel',
 'doezum',
 'langeweg',
 'boven leeuwen',
 'beek ubbergen',
 'griendtsveen',
 'lochem',
 'putten',
 'berg en terblijt',
 'azewijn',
 'earnewald',
 'doorwerth',
 'hoogkerk',
 'epen',
 'den  haag',
 'drempt',
 'bad nieuweschans',
 'westerhocen',
 'enmen',
 'landsmeer',
 'som',
 'elst(ut)',
 'twisk',
 'middelstum',
 'loosbroek',
 'hoensbroek',
 'beek',
 'tytsjerk',
 'harfsen',
 'hemrik',
 'oudega',
 'edam',
 'spaubeek',
 'baflo',
 'flevoland',
 'oost-maarland',
 'almere  - buiten',
 'almere - buiten',
 'westerhoven',
 'valkenburg aan de geul',
 'ridderker',
 'rijsbergen',
 'willemstaf',
 'halfweg',
 'winterswijk-meddo',
 'wagenberg',
 'schijf',
 'wernhout',
 'schalkhaar',
 'wormerveer',
 'froombosch',
 'wijnjewoude',
 'loppersum',
 'asteb',
 'zwaagwesteinde',
 'zuidoostbeemster',
 'hoonhorst/dalfsen',
 'rozenburg',
 'steggerda',
 'sint-oedenrode',
 'milheeze',
 'zeijen',
 'eede',
 'batenburg',
 'lutjegast',
 'velsen-noord',
 'berghem',
 'puiflijk',
 'nijmgen',
 'genhout',
 'aarle-rixtel',
 'broek in waterland',
 'mheer',
 'hattem',
 'borkel en schaft',
 'son & breugel',
 'oirsbeek',
 'vlagtwedde',
 'heerken',
 ...]

In [159]:
print(cityLatLong)

                       city        lat      long
0               ijsselstein  52.026205  5.028686
1                 hilversum  52.231587  5.173494
2                  deventer  52.249273  6.176131
3                     assen  52.990372  6.553378
4                nieuwlande  52.691313  6.616811
5               winterswijk  51.974731  6.722405
6                  westzaan  52.456813  4.773083
7                    geffen  51.742292  5.462088
8          heeswijk-dinther  51.664083  5.466635
9                    almere  52.441759  5.209315
10                    breda  51.564448  4.751230
11         emmer compascuum  52.805873  7.010427
12                 ter apel  52.877717  7.068111
13                  heerlen  50.876277  5.982795
14                amsterdam  52.374540  4.897976
15                  huissen  51.934410  5.932849
16                hoogeveen  52.719244  6.465282
17                  zutphen  52.143222  6.204444
18                   leiden  52.151816  4.481109
19                 ugchelen  52.169262  5.900451
20               oosterhout  51.644472  4.851366
21                polsbroek  51.987055  4.873784
22                 lelystad  52.536681  5.361072
23                rotterdam  51.927798  4.488623
24                hoogezand  53.133009  6.785634
25               bodegraven  52.092861  4.747455
26                  bantega  52.830288  5.794892
27      berkel en rodenrijs  51.997348  4.470393
28                 aalsmeer  52.265834  4.766170
29                coevorden  52.652662  6.739324
...                     ...        ...       ...
1000             zuidermeer  52.663999  4.975520
1001      oostwold, oldambt  53.215652  7.043184
1002              born (lb)  51.044839  5.837633
1003            roodeschool  53.414617  6.781603
1004            herkenbosch  51.168353  6.102692
1005               avenhorn  52.617738  4.969920
1006                warmond  52.200897  4.525958
1007         surhuisterveen  53.172683  6.154054
1008                de rijp  52.556173  4.842247
1009       sint philipsland  51.633265  4.160483
1010          lichtenvoorde  51.993944  6.565700
1011               macharen  51.802675  5.542677
1012                  megen  51.817166  5.566282
1013    valkenburg a/d geul        NaN       NaN
1014          nieuwe pekela  53.055781  6.960637
1015                  stein  50.973938  5.760869
1016                   lent  51.865864  5.865092
1017           zuid holland  51.996679  4.559740
1018         den hoorn (zh)  52.003360  4.325468
1019  lennisheuvel (boxtel)  51.574320  5.316120
1020               drieborg  53.257924  7.175475
1021                liessel  51.411651  5.830435
1022                   vilt  50.857585  5.809624
1023             nieuwstadt  51.042089  5.861236
1024                   born  51.044839  5.837633
1025            nieuweroord  52.725450  6.564840
1026             noordwolde  52.891558  6.135962
1027             appelascha        NaN       NaN
1028        beneden-leeuwen  51.872420  5.514564
1029               neerbeek  51.256195  5.984346

[1030 rows x 3 columns]

In [135]:
valueWithLeerlingen

5
Anders of combinatie                      3452
Directie of IB-er etc...                  4417
Gepensioneerde voor de klas               1119
Invaller via detacheringsbureau           3656
Klas naar huis sturen                    15617
Klas naar huis sturen                       95
Klas verdelen                             9253
Klas verdelen                              264
Onbevoegde voor de klas                   7856
Onbevoegde voor de klas                     89
Ouder met lesbevoegdheid voor de klas      103
Parttimer komt extra dag terug            3258
Name: 4, dtype: int64

Pak alle steden die nu voor komen in het timefiltered ding. 
Doe een map functie voor ieder element:
- kijk wat de meest voorkomende oplossing is. 
- Gebruik een dictionary met als key oplossing en als value een kleur om de juiste kleur te returnen.

In [189]:
def calculateMarkerColor(dataframe, cityName):
    colors = {
        'A.Klas naar huis sturen': 'rgb(215,48,39)',
        'B.Staking': 'rgb(244,109,67)',
        'C.Onbevoegde voor de klas': 'rgb(253,174,97)',
        'D.Klas verdelen':'rgb(254,224,139)',
        'E.Parttimer komt extra dag terug': 'rgb(217,239,139)',
        'F.Directie of IB-er etc...':'rgb(166,217,106)',
        'G.Ouder met lesbevoegdheid voor de klas':'rgb(102,189,99)',
        'H.Gepensioneerde voor de klas':'rgb(26,152,80)',
        'I.Invaller via detacheringsbureau':'rgb(18,106,56)',
        'J.Anders of combinatie':'rgb(220,220,220)' }

    lt_value=dataframe[dataframe[2].str.contains(cityName)]
    value_vs_rest=pd.DataFrame([lt_value.groupby(5)[4].sum()] ).T
    if value_vs_rest.size:
        color = colors[value_vs_rest.idxmax()[4]]
    else:
        color='rgb(0,0,0)'
    return color

In [188]:
lt=pd.read_csv('export.csv', sep=';', 
               error_bad_lines=False,header=None)
lt.head()
lt.fillna(0)
for c in [1,2,3]:
    lt[c]=lt[c].str.strip().str.lower()
lt[5]=lt[5].str.strip().str.replace('(', '').str.replace(')', '')
slider = [1,6]
lt[0]=pd.to_datetime(lt[0])
cityLatLong = pd.read_csv('cityLatLong.csv', sep='\t', index_col=False )

cityLatLong['city'] = cityLatLong['city'].str.replace('(', '').str.replace(')', '')
timeFilteredDF = lt[(lt[0]>=datetime.date(2018, slider[0] ,1)) & (lt[0]<datetime.date(2018 ,slider[1]+1 ,1))]
    #print('cityLatLong', cityLatLong)
uniqueTimeFilteredDF = cityLatLong.loc[cityLatLong['city'].isin(timeFilteredDF[2].unique())]

joe = [calculateMarkerColor(timeFilteredDF, x) for x in list(uniqueTimeFilteredDF['city'])]

In [199]:
uniqueTimeFilteredDF.to_csv('cityLatLong.csv', sep='\t', index_col=False)

In [200]:
cityLatLong = pd.read_csv('cityLatLong.csv', sep='\t', index_col=False)

In [213]:
cityLatLong = cityLatLong[['city', 'lat', 'long']]

In [215]:
cityLatLong['color'] = joe

In [218]:
cityLatLong.to_csv('cityLatLong.csv', sep='\t')

In [219]:
bla = pd.read_csv('cityLatLong.csv', sep='\t', index_col=False)

In [220]:
bla

      Unnamed: 0                 city        lat      long             color
0              0          ijsselstein  52.026205  5.028686    rgb(215,48,39)
1              1            hilversum  52.231587  5.173494   rgb(253,174,97)
2              2             deventer  52.249273  6.176131  rgb(217,239,139)
3              3                assen  52.990372  6.553378    rgb(215,48,39)
4              4           nieuwlande  52.691313  6.616811  rgb(217,239,139)
5              5          winterswijk  51.974731  6.722405    rgb(215,48,39)
6              6             westzaan  52.456813  4.773083    rgb(215,48,39)
7              7               geffen  51.742292  5.462088  rgb(254,224,139)
8              8     heeswijk-dinther  51.664083  5.466635  rgb(220,220,220)
9              9               almere  52.441759  5.209315  rgb(220,220,220)
10            10                breda  51.564448  4.751230    rgb(215,48,39)
11            11     emmer compascuum  52.805873  7.010427  rgb(220,220,220)
12            12             ter apel  52.877717  7.068111    rgb(215,48,39)
13            13              heerlen  50.876277  5.982795    rgb(215,48,39)
14            14            amsterdam  52.374540  4.897976    rgb(215,48,39)
15            15              huissen  51.934410  5.932849  rgb(217,239,139)
16            16            hoogeveen  52.719244  6.465282    rgb(215,48,39)
17            17              zutphen  52.143222  6.204444  rgb(220,220,220)
18            18               leiden  52.151816  4.481109   rgb(253,174,97)
19            19             ugchelen  52.169262  5.900451  rgb(217,239,139)
20            20           oosterhout  51.644472  4.851366  rgb(254,224,139)
21            21            polsbroek  51.987055  4.873784   rgb(253,174,97)
22            22             lelystad  52.536681  5.361072    rgb(215,48,39)
23            23            rotterdam  51.927798  4.488623   rgb(253,174,97)
24            24            hoogezand  53.133009  6.785634    rgb(215,48,39)
25            25           bodegraven  52.092861  4.747455  rgb(166,217,106)
26            26              bantega  52.830288  5.794892  rgb(217,239,139)
27            27  berkel en rodenrijs  51.997348  4.470393  rgb(254,224,139)
28            28             aalsmeer  52.265834  4.766170  rgb(217,239,139)
29            29            coevorden  52.652662  6.739324   rgb(253,174,97)
...          ...                  ...        ...       ...               ...
990          990           vlagtwedde  53.014100  7.124079    rgb(215,48,39)
991          991              heerken        NaN       NaN   rgb(253,174,97)
992          992           zuidermeer  52.663999  4.975520    rgb(215,48,39)
993          993    oostwold, oldambt  53.215652  7.043184  rgb(166,217,106)
994          994          roodeschool  53.414617  6.781603    rgb(18,106,56)
995          995          herkenbosch  51.168353  6.102692  rgb(254,224,139)
996          996             avenhorn  52.617738  4.969920  rgb(217,239,139)
997          997              warmond  52.200897  4.525958    rgb(215,48,39)
998          998       surhuisterveen  53.172683  6.154054    rgb(18,106,56)
999          999              de rijp  52.556173  4.842247  rgb(220,220,220)
1000        1000     sint philipsland  51.633265  4.160483    rgb(215,48,39)
1001        1001        lichtenvoorde  51.993944  6.565700  rgb(220,220,220)
1002        1002             macharen  51.802675  5.542677  rgb(220,220,220)
1003        1003                megen  51.817166  5.566282  rgb(220,220,220)
1004        1004  valkenburg a/d geul        NaN       NaN   rgb(253,174,97)
1005        1005        nieuwe pekela  53.055781  6.960637    rgb(215,48,39)
1006        1006                stein  50.973938  5.760869    rgb(215,48,39)
1007        1007                 lent  51.865864  5.865092    rgb(215,48,39)
1008        1008         zuid holland  51.996679  4.559740  rgb(254,224,139)
1009        1009         den hoorn zh  52.003360  4.325468   rgb(253,174,97)
1010        1010             drieborg  53.257924  7.175475   rgb(253,174,97)
1011        1011              liessel  51.411651  5.830435  rgb(166,217,106)
1012        1012                 vilt  50.857585  5.809624  rgb(220,220,220)
1013        1013           nieuwstadt  51.042089  5.861236    rgb(215,48,39)
1014        1014                 born  51.044839  5.837633  rgb(217,239,139)
1015        1015          nieuweroord  52.725450  6.564840  rgb(217,239,139)
1016        1016           noordwolde  52.891558  6.135962  rgb(166,217,106)
1017        1017           appelascha        NaN       NaN  rgb(217,239,139)
1018        1018      beneden-leeuwen  51.872420  5.514564  rgb(217,239,139)
1019        1019             neerbeek  51.256195  5.984346    rgb(215,48,39)

[1020 rows x 5 columns]